### ISSUE TITLE
No tests are generated

### ISSUE THREAD

**Issue by FBurner** [paul-thebaud/phpunitgen-core#8]
## Expected Behavior
Completly generated tests

## Actual Behavior

only get 
/** @todo This test is incomplete. */

## Steps to Reproduce the Problem

  1.  ./vendor/bin/phpunitgen src/Class.php

## Specifications

  - Version: 1.0
  - Platform: windows

**Comment by FBurner** [comment]
ITs in case i use class provided via the method like

test->(new Class)

test(Class $test) {
   return $test->getString();
}

is possible to get this generated otherwise it seems only to test trivial code where i do not really need unit tests?

**Comment by paul-thebaud** [comment]
Hello,

PhpUnitGen is not meant to generate the content of your tests (except for getters/setters methods), because of the two following points :
- Inspecting the code to generate the appropriate test is way to complex.
- The generated test might miss some features that your code implement, or mark them as "passed" even if those are wrong.

I will soon add a note on this on the README and documentation's index page to avoid confusion.

**Comment by paul-thebaud** [comment]
Hi, I added the notice on all repositories README files and on the documentation, so I'm closing this issue.
If you have any other question, feel free to reopen or create a new issue.
